/*
 * © Bart Kampers
 */
package bka.demo.clock;

import java.io.*;
import java.util.*;
import java.util.logging.*;
import java.util.stream.*;

/**
 *
 * @author bartkampers
 */
public class WeatherStationFrame extends javax.swing.JFrame {

    public WeatherStationFrame() {
        initComponents();
        Timer timer = new Timer();
        timer.schedule(new DataReaderTask(), 0, 10 * 60 * 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel controlPanel = new javax.swing.JPanel();
        javax.swing.JPanel weatherPanelPlaceholder = weatherPanel;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather Station");

        stationComboBox.setModel(stationComboBoxModel);
        stationComboBox.setEnabled(false);
        stationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout weatherPanelPlaceholderLayout = new javax.swing.GroupLayout(weatherPanelPlaceholder);
        weatherPanelPlaceholder.setLayout(weatherPanelPlaceholderLayout);
        weatherPanelPlaceholderLayout.setHorizontalGroup(
            weatherPanelPlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        weatherPanelPlaceholderLayout.setVerticalGroup(
            weatherPanelPlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(weatherPanelPlaceholder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationComboBoxActionPerformed
        synchronized (mutex) {
            Object selectedName = stationComboBoxModel.getSelectedItem();
            if (selectedName != null) {
                weatherPanel.setStation(stations.stream().filter(station -> selectedName.equals(station.getStationName())).findAny().get());
            }
            else {
                weatherPanel.setStation(null);
            }
        }
    }//GEN-LAST:event_stationComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WeatherStationFrame().setVisible(true);
        });
    }

    private class DataReaderTask extends TimerTask {

        @Override
        public void run() {
            try {
                synchronized (mutex) {
                    stations = WeatherStationReader.getStations();
                    String selected = (String) stationComboBoxModel.getSelectedItem();
                    stationNames = stations.stream().map(station -> normalizedForAlphabet(station.getStationName())).sorted().collect(Collectors.toList());
                    stationComboBoxModel.removeAllElements();
                    stationComboBoxModel.addAll(stationNames);
                    if (stationNames.contains(selected)) {
                        stationComboBoxModel.setSelectedItem(selected);
                    }
                    else {
                        stationComboBoxModel.setSelectedItem(null);
                    }
                    stationComboBox.setEnabled(true);
                }
            }
            catch (IOException ex) {
                Logger.getLogger(WeatherStationFrame.class.getName()).log(Level.WARNING, "Stations could not be retrieved", ex);
            }
        }

        private String normalizedForAlphabet(String string) {
           String prefix = getPrefix(string);
            if (prefix == null) {
               return string;
            }
            return string.substring(prefix.length() + 1) + ", " + prefix;
        }

        private String getPrefix(String string) {
            for (String prefix : prefixes) {
                if (string.startsWith(prefix+' ')) {
                    return prefix;
                }
            }
            return null;
        }

        private Collection<String> stationNames;

        private final String[] prefixes = { "De", "Den", "Het", "'t", "Ter" };

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JComboBox<String> stationComboBox = new javax.swing.JComboBox<>();
    // End of variables declaration//GEN-END:variables

    private final WeatherStationPanel weatherPanel = new WeatherStationPanel();
    private final javax.swing.DefaultComboBoxModel<String> stationComboBoxModel = new javax.swing.DefaultComboBoxModel<>();

    private Collection<WeatherStation> stations;

    private static final Object mutex = new Object();

}
