/*
** © Bart Kampers
*/
package bka.demo.graphs;

import bka.awt.*;
import bka.awt.graphcanvas.*;
import bka.awt.graphcanvas.history.*;
import bka.swing.popup.*;
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.*;
import java.util.List;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;
import javax.swing.*;

public class GraphEditorDemo extends JFrame {

    public GraphEditorDemo() {
        initComponents();
        BasicStroke solidStroke = new BasicStroke();
        ellipsPaintable.setStroke(BORDER_STROKE_KEY, solidStroke);
        ellipsPaintable.setPaint(BORDER_PAINT_KEY, Color.BLACK);
        ellipsPaintable.setPaint(FILL_PAINT_KEY, Color.BLACK);
        rectanglePaintable.setStroke(BORDER_STROKE_KEY, solidStroke);
        rectanglePaintable.setPaint(BORDER_PAINT_KEY, Color.BLACK);
        rectanglePaintable.setPaint(FILL_PAINT_KEY, Color.WHITE);
        populateVertexSelectorPanel(List.of(ellipsPaintable, rectanglePaintable));
        canvas.getDrawHistory().addListener(this::updateHistoryList);
        historyList.addMouseListener(new HistoryListMouseAdapter());
        historyList.addKeyListener(new HistoryListKeyAdapter());
    }

    private void updateHistoryList(DrawHistory history) {
        historyListModel.removeAllElements();
        history.getMutattions().forEach(mutation -> historyListModel.addElement(getBundleText(mutation.getBundleKey())));
        if (history.getIndex() > 0) {
            int index = history.getIndex() - 1;
            historyList.setSelectedIndex(index);
            Rectangle selection = historyList.getCellBounds(index, index);
            historyScrollPane.getViewport().scrollRectToVisible(selection);
            historyScrollPane.getVerticalScrollBar().setValue(selection.y);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edgeSelector = new javax.swing.ButtonGroup();
        javax.swing.JScrollPane graphScrollPane = new javax.swing.JScrollPane();
        graphPanel = new GraphPanel();
        historyPanel = new javax.swing.JPanel();
        historyScrollPane = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList<>();
        historyList.setCellRenderer(new HistoryListCellRenderer());
        componentPanel = new javax.swing.JPanel();
        vertexSelectorPanel = new javax.swing.JPanel();
        undirectedEdgeRadioButton = new javax.swing.JRadioButton();
        directedEdgeRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(BUNDLE.getString("ApplicationTitle"));

        graphScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        graphScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        graphPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                graphPanelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                graphPanelMouseMoved(evt);
            }
        });
        graphPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                graphPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                graphPanelMouseReleased(evt);
            }
        });
        graphPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                graphPanelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                graphPanelKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        graphScrollPane.setViewportView(graphPanel);

        getContentPane().add(graphScrollPane, java.awt.BorderLayout.CENTER);

        historyPanel.setLayout(new javax.swing.BoxLayout(historyPanel, javax.swing.BoxLayout.LINE_AXIS));

        historyScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        historyScrollPane.setMinimumSize(new java.awt.Dimension(150, 400));
        historyScrollPane.setPreferredSize(new java.awt.Dimension(150, 400));

        historyList.setModel(historyListModel);
        historyList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        historyScrollPane.setViewportView(historyList);

        historyPanel.add(historyScrollPane);

        getContentPane().add(historyPanel, java.awt.BorderLayout.EAST);

        vertexSelectorPanel.setLocation(new java.awt.Point(0, 5));
        vertexSelectorPanel.setLayout(new javax.swing.BoxLayout(vertexSelectorPanel, javax.swing.BoxLayout.Y_AXIS));

        edgeSelector.add(undirectedEdgeRadioButton);
        undirectedEdgeRadioButton.setSelected(true);
        undirectedEdgeRadioButton.setText(BUNDLE.getString("UndirectedEdge"));

        edgeSelector.add(directedEdgeRadioButton);
        directedEdgeRadioButton.setText(BUNDLE.getString("DirectedEdge"));

        javax.swing.GroupLayout componentPanelLayout = new javax.swing.GroupLayout(componentPanel);
        componentPanel.setLayout(componentPanelLayout);
        componentPanelLayout.setHorizontalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directedEdgeRadioButton)
                    .addComponent(undirectedEdgeRadioButton))
                .addContainerGap())
            .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentPanelLayout.createSequentialGroup()
                    .addContainerGap(76, Short.MAX_VALUE)
                    .addComponent(vertexSelectorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        componentPanelLayout.setVerticalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(undirectedEdgeRadioButton)
                .addGap(18, 18, 18)
                .addComponent(directedEdgeRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(246, 246, 246))
            .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentPanelLayout.createSequentialGroup()
                    .addContainerGap(236, Short.MAX_VALUE)
                    .addComponent(vertexSelectorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        getContentPane().add(componentPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graphPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMouseClicked
        updateGraphPanel(canvas.handleMouseClicked(evt));
    }//GEN-LAST:event_graphPanelMouseClicked

    private void graphPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMouseDragged
        updateGraphPanel(canvas.handleMouseDragged(evt));
    }//GEN-LAST:event_graphPanelMouseDragged

    private void graphPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMousePressed
        updateGraphPanel(canvas.handleMousePressed(evt));
    }//GEN-LAST:event_graphPanelMousePressed

    private void graphPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMouseReleased
        updateGraphPanel(canvas.handleMouseReleased(evt));
        graphPanel.requestFocus();
    }//GEN-LAST:event_graphPanelMouseReleased

    private void graphPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMouseMoved
        updateGraphPanel(canvas.handleMouseMoved(evt));
    }//GEN-LAST:event_graphPanelMouseMoved

    private void graphPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_graphPanelKeyReleased
        updateGraphPanel(canvas.handleKeyReleased(evt));
    }//GEN-LAST:event_graphPanelKeyReleased

    private void graphPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_graphPanelKeyPressed
        updateGraphPanel(canvas.handleKeyPressed(evt));
    }//GEN-LAST:event_graphPanelKeyPressed

    private void populateVertexSelectorPanel(List<VertexPaintable> renderers) {
        renderers.forEach(renderer -> {
            JToggleButton button = new JToggleButton();
            vertexButtons.put(button, renderer);
            button.setIcon(createIcon(renderer));
            button.addActionListener(event -> {
                if (((JToggleButton) event.getSource()).isSelected()) {
                    vertexButtons.keySet().stream()
                        .filter(vertexButton -> !vertexButton.equals(event.getSource()))
                        .forEach(vertexButton -> vertexButton.setSelected(false));
                }
            });
            vertexSelectorPanel.add(button);
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SelectNimbusLookAndFeel();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraphEditorDemo().setVisible(true));
    }

    private static void SelectNimbusLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    return;
                }
            }
        }
        catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphEditorDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void updateGraphPanel(ComponentUpdate update){
        if (java.awt.Cursor.DEFAULT_CURSOR <= update.getCursorType() && update.getCursorType() <= java.awt.Cursor.MOVE_CURSOR) {
            setGraphPanelCursor(update.getCursorType());
        }
        if (update.needsRepeaint()) {
            graphPanel.repaint();
        }
    }

    private void setGraphPanelCursor(int type) {
        if (graphPanel.getCursor().getType() != type) {
            graphPanel.setCursor(new java.awt.Cursor(type));
        }
    }

    private static String getBundleText(String key) {
        if (!BUNDLE.containsKey(key)) {
            return "<html><i>" + key + "</i></html>";
        }
        return BUNDLE.getString(key);
    }


    private class GraphPanel extends javax.swing.JPanel {

        @Override
        public void paint(java.awt.Graphics graphics) {
            super.paint(graphics);
            canvas.paint((java.awt.Graphics2D) graphics);
        }
    }


    private class HistoryListCellRenderer extends javax.swing.DefaultListCellRenderer {

        @Override
        public java.awt.Component getListCellRendererComponent(javax.swing.JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            java.awt.Component renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (isSelected) {
                renderer.setForeground(java.awt.Color.BLACK);
            }
            else if (index < canvas.getDrawHistory().getIndex()) {
                renderer.setForeground(java.awt.Color.BLACK);
            }
            else {
                renderer.setForeground(java.awt.Color.GRAY);
            }
            return renderer;
        }
    }


    private class HistoryListMouseAdapter extends java.awt.event.MouseAdapter {

        @Override
        public void mouseReleased(java.awt.event.MouseEvent event) {
            int target = historyList.getSelectedIndex() + 1;
            if (canvas.getDrawHistory().getIndex() != target) {
                while (canvas.getDrawHistory().getIndex() < target) {
                    canvas.getDrawHistory().redo();
                }
                while (canvas.getDrawHistory().getIndex() > target) {
                    canvas.getDrawHistory().undo();
                }
                graphPanel.repaint();
            }
        }
    }


    private class HistoryListKeyAdapter extends java.awt.event.KeyAdapter {

        @Override
        public void keyReleased(java.awt.event.KeyEvent event) {
            if (Keyboard.getInstance().isUndo(event)) {
                canvas.getDrawHistory().undo();
                graphPanel.repaint();
            }
            else if (Keyboard.getInstance().isRedo(event)) {
                canvas.getDrawHistory().redo();
                graphPanel.repaint();
            }
        }
    }

    private GraphCanvas getCanvas() {
        return canvas;
    }

    private static Rectangle colorChooserBounds(Point location) {
        return new Rectangle(location.x, location.y, 600, 300);
    }

    private static Color castToColor(Paint paint) {
        if (paint instanceof Color) {
            return (Color) paint;
        }
        return null;
    }

    private static Icon createIcon(Paintable paintable) {
        return createIcon(paintable, null);
    }

    private static Icon createIcon(Paintable paintable, Color highlight) {
        BufferedImage image = new BufferedImage(15, 15, BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = image.createGraphics();
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        graphics.translate(image.getWidth() / 2, image.getHeight() / 2);
        paintable.paint(graphics);
        ImageIcon icon = new ImageIcon(image);
        return icon;
    }

    private final GraphCanvas canvas = new GraphCanvas(new ApplicationContext() {

        @Override
        public void showVertexMenu(VertexRenderer vertex, Point location) {
            JPopupMenu menu = new JPopupMenu();
            addPaintMenus(vertex, location, menu);
            if (menu.getComponentCount() > 0) {
                menu.show(graphPanel, location.x, location.y);
            }
        }
        
        @Override
        public void showEdgeMenu(EdgeRenderer edge, Point location) {
            JPopupMenu menu = new JPopupMenu();
            JCheckBoxMenuItem directedMenuItem = new JCheckBoxMenuItem(getBundleText("Directed"), edge.isDirected());
            directedMenuItem.addActionListener(evt -> getCanvas().setDirected(edge, directedMenuItem.getState()));
            menu.add(directedMenuItem, edge.isDirected());
            if (edge.isDirected()) {
                JMenuItem revertMenuItem = new JMenuItem(getBundleText("Revert"));
                revertMenuItem.addActionListener(evt -> getCanvas().revert(edge));
                menu.add(revertMenuItem);
            }
            addPaintMenus(edge, location, menu);
            menu.show(graphPanel, location.x, location.y);
        }

        private void addPaintMenus(Element element, Point location, JPopupMenu menu) {
            element.getCustomizablePaintables().forEach(paintable -> {
                paintable.getPaintKeys().forEach(paintKey -> {
                    JMenuItem paintItem = new JMenuItem(getBundleText(paintKey.toString()));
                    paintItem.addActionListener(evt -> pickColor(location, paintable, paintKey));
                    menu.add(paintItem);
                });
            });
        }

        public final void pickColor(Point location, Paintable paintable, Object key) {
            PopupControl.show(
                graphPanel,
                new ColorChooserPopupModel(
                    graphPanel,
                    colorChooserBounds(location),
                    castToColor(paintable.getPaint(key)),
                    newColor -> getCanvas().changePaint(paintable, key, newColor)));
        }

        @Override
        public void editString(String input, Point location, Consumer<String> onApply) {
            PopupControl.show(
                graphPanel,
                new TextFieldPopupModel(
                    new Rectangle(location.x - POPUP_WIDTH / 2, location.y - POPUP_HEIGHT / 2, POPUP_WIDTH, POPUP_HEIGHT),
                    input,
                    onApply)
            );
        }

        @Override
        public void requestUpdate(ComponentUpdate update) {
            updateGraphPanel(update);
        }

        @Override
        public VertexRenderer createVertexRenderer(Point location) {
            JToggleButton vertexButton = vertexButtons.keySet().stream()
                .filter(toggleButton -> toggleButton.isSelected())
                .findAny().orElse(null);
            if (vertexButton == null) {
                return null;
            }
            VertexPaintable vertexPaintable = vertexButtons.get(vertexButton);
            if (vertexPaintable instanceof RoundVertexPaintable) {
                return new VertexRenderer(new RoundVertexPaintable(vertexPaintable), location);
            }
            if (vertexPaintable instanceof SquareVertexPaintable) {
                return new VertexRenderer(new SquareVertexPaintable(vertexPaintable), location);
            }
            throw new IllegalStateException();
        }

        @Override
        public EdgeRenderer createEdgeRenderer(VertexRenderer origin) {
            EdgeRenderer edgeRenderer = new EdgeRenderer(origin);
            edgeRenderer.setDirected(directedEdgeRadioButton.isSelected());
            return edgeRenderer;
        }

        private static final int POPUP_WIDTH = 50;
        private static final int POPUP_HEIGHT = 20;

    });


    private class RoundVertexPaintable extends VertexPaintable {

        public RoundVertexPaintable(Dimension size) {
            super(size);
        }

        public RoundVertexPaintable(VertexPaintable vertexPaintable) {
            super(vertexPaintable);
        }

        @Override
        public void paint(Graphics2D graphics) {
            fill(graphics);
            paint(graphics, getPaint(BORDER_PAINT_KEY), getStroke(BORDER_STROKE_KEY));
        }

        @Override
        public void paint(Graphics2D graphics, Paint paint, Stroke stroke) {
            graphics.setPaint(paint);
            graphics.setStroke(stroke);
            graphics.drawOval(-widthRadius(), -heightRadius(), getSize().width, getSize().height);
        }

        private void fill(Graphics2D graphics) {
            graphics.setPaint(getPaint(FILL_PAINT_KEY));
            graphics.fillOval(-widthRadius(), -heightRadius(), getSize().width, getSize().height);
        }

        private int widthRadius() {
            return getSize().width / 2;
        }

        private int heightRadius() {
            return getSize().height / 2;
        }
    };


    private class SquareVertexPaintable extends VertexPaintable {

        public SquareVertexPaintable(Dimension size) {
            super(size);
        }

        public SquareVertexPaintable(VertexPaintable vertexPaintable) {
            super(vertexPaintable);
        }

        @Override
        public void paint(Graphics2D graphics) {
            fill(graphics);
            paint(graphics, getPaint(BORDER_PAINT_KEY), getStroke(BORDER_STROKE_KEY));
        }

        @Override
        public void paint(Graphics2D graphics, Paint paint, Stroke stroke) {
            graphics.setPaint(paint);
            graphics.setStroke(stroke);
            graphics.drawRect(-widthRadius(), -heightRadius(), getSize().width, getSize().height);
        }

        private void fill(Graphics2D graphics) {
            graphics.setPaint(getPaint(FILL_PAINT_KEY));
            graphics.fillRect(-widthRadius(), -heightRadius(), getSize().width, getSize().height);
        }


        @Override
        public double distance(Point location, Point point) {
            double distance = Math.sqrt(
                countour2D(location).stream()
                    .map(line -> squareDistance(point, line))
                    .sorted()
                    .findFirst().get());
            return (new Rectangle(topLeft(location), getSize()).contains(point)) ? -distance : distance;
        }

        public long squareDistance(Point2D point, Line2D line) {
            return CanvasUtil.squareDistance(CanvasUtil.round(point), CanvasUtil.round(line.getP1()), CanvasUtil.round(line.getP2()));
        }

//        @Override
//        public Supplier<Point> distancePositioner(Point location, Point point) {
////            double dy = point.y - location.y;
////            double angle = Math.atan((point.x - location.x) / dy);
////            float sin = (float) ((dy < 0) ? -Math.sin(angle) : Math.sin(angle));
////            float cos = (float) ((dy < 0) ? -Math.cos(angle) : Math.cos(angle));
////            float distanceToBorder = (float) distance(location, point);
////            return () -> {
////                float distanceToLocation = getSize().width / 2f + distanceToBorder;
////                return new Point(location.x + Math.round(sin * distanceToLocation), location.y + Math.round(cos * distanceToLocation));
////            };
//            long distance = Long.MAX_VALUE;
//            int index = -1;
//            List<Line2D> contour = countour2D(location);
//            for (int i = 0; i < contour.size(); ++i) {
//                if (squareDistance(point, contour.get(i)) < distance) {
//                    index = i;
//                    distance = squareDistance(point, contour.get(i));
//                }
//            }
//            Function<Integer, Point> pointAt = idx -> {
//                if (idx < contour.size()) {
//                    return CanvasUtil.round(contour.get(idx).getP1());
//                }
//                return CanvasUtil.round(contour.get(0).getP1());
//            };
//            Point linePoint1 = pointAt.apply(index);
//            Point linePoint2 = pointAt.apply(index + 1);
//            Point2D anchor = CanvasUtil.intersectionPoint(point, linePoint1, linePoint2);
//            double yDistance = directedDistance(point, anchor, CanvasUtil.slope(linePoint1, linePoint2));
//            double xDistance = (linePoint1.x > linePoint2.x) ? -yDistance : yDistance;
////            contour.stream().forEach((Line2D line) -> {
////                line.getP1().setLocation(line.getX1() + location.x, line.getY1() + location.y);
////                line.getP2().setLocation(line.getX2() + location.x, line.getY2() + location.y);
////            });
//            return new DistanceToLinePositioner(index, xDistance, yDistance, directedRatio(linePoint1, linePoint2, anchor), pointAt);
//        }

//        private double directedDistance(Point2D distantPoint, Point2D anchor, double slope) {
//            double distance = distantPoint.distance(anchor);
//            if (slope <= -1) {
//                return (distantPoint.getX() < anchor.getX()) ? -distance : distance;
//            }
//            if (1 <= slope) {
//                return (distantPoint.getX() > anchor.getX()) ? -distance : distance;
//            }
//            return (distantPoint.getY() < anchor.getY()) ? -distance : distance;
//        }
//
//        private double directedRatio(Point2D linePoint1, Point2D linePoint2, Point2D anchor) {
//            double ratio = anchor.distance(linePoint1) / linePoint1.distance(linePoint2);
//            double x1 = linePoint1.getX();
//            double x2 = linePoint2.getX();
//            double y1 = linePoint1.getY();
//            double y2 = linePoint2.getY();
//            if (Math.abs(CanvasUtil.slope(linePoint1, linePoint2)) < 1) {
//                if (anchor.getX() < x1 && x1 < x2 || x2 < x1 && x1 < anchor.getX()) {
//                    return -ratio;
//                }
//            }
//            else {
//                if (anchor.getY() < y1 && y1 < y2 || y2 < y1 && y1 < anchor.getY()) {
//                    return -ratio;
//                }
//            }
//            return ratio;
//        }

        @Override
        public Point getConnectorPoint(Point location, Point point) {
            if (location.equals(point)) {
                return point;
            }
            Point2D nearest = null;
            for (Point2D intersectionPoint : intersectionPoints(location, Line.through(location, point))) {
                if (nearest == null || Math.abs(nearest.distance(point)) > Math.abs(intersectionPoint.distance(point))) {
                    nearest = intersectionPoint;
                }
            }
            return (nearest == null) ? location : CanvasUtil.round(nearest);
        }

        private List<Point2D> intersectionPoints(Point location, Line incomming) {
            return contour(location).stream()
                .map(contourLine -> contourLine.intersection(incomming))
                .flatMap(optional -> optional.isPresent() ? Stream.of(optional.get()) : Stream.empty())
                .filter(intersectionPoint -> inBounds(intersectionPoint, location))
                .collect(Collectors.toList());
        }

        private boolean inBounds(Point2D intersectionPoint, Point location) {
            return location.x - widthRadius() <= intersectionPoint.getX() && intersectionPoint.getX() <= location.x + widthRadius()
                && location.y - heightRadius() <= intersectionPoint.getY() && intersectionPoint.getY() <= location.y + heightRadius();
        }

        private List<Line> contour(Point location) {
            return countour2D(location).stream().map(line -> Line.through(line.getP1(), line.getP2())).collect(Collectors.toList());
        }

        private List<Line2D> countour2D(Point location) {
            return List.of(
                new Line2D.Double(topLeft(location), bottomLeft(location)),
                new Line2D.Double(bottomLeft(location), bottomRight(location)),
                new Line2D.Double(bottomRight(location), topRight(location)),
                new Line2D.Double(topRight(location), topLeft(location))
            );
        }

        private Point topLeft(Point location) {
            return new Point(location.x - widthRadius(), location.y - heightRadius());
        }

        private Point topRight(Point location) {
            return new Point(location.x + widthRadius(), location.y - heightRadius());
        }

        private Point bottomLeft(Point location) {
            return new Point(location.x - widthRadius(), location.y + heightRadius());
        }

        private Point bottomRight(Point location) {
            return new Point(location.x + widthRadius(), location.y + heightRadius());
        }

        private int widthRadius() {
            return getSize().width / 2;
        }

        private int heightRadius() {
            return getSize().height / 2;
        }

    };


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel componentPanel;
    private javax.swing.JRadioButton directedEdgeRadioButton;
    private javax.swing.ButtonGroup edgeSelector;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JList<String> historyList;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JScrollPane historyScrollPane;
    private javax.swing.JRadioButton undirectedEdgeRadioButton;
    private javax.swing.JPanel vertexSelectorPanel;
    // End of variables declaration//GEN-END:variables

    private final Map<JToggleButton, VertexPaintable> vertexButtons = new HashMap<>();

    private final javax.swing.DefaultListModel<String> historyListModel = new javax.swing.DefaultListModel<>();

    private static final ResourceBundle BUNDLE = ResourceBundle.getBundle("GraphEditor");

    private static final Dimension VERTEX_ICON_DIMENSION = new Dimension(12, 12);

    private final static Object BORDER_PAINT_KEY = "BorderPaint";
    private final static Object BORDER_STROKE_KEY = "BorderStroke";
    private final static Object FILL_PAINT_KEY = "FillPaint";

    private final RoundVertexPaintable ellipsPaintable = new RoundVertexPaintable(VERTEX_ICON_DIMENSION);
    private final SquareVertexPaintable rectanglePaintable = new SquareVertexPaintable(VERTEX_ICON_DIMENSION);

}
